 

services:
  # Service Laravel (App)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: garage-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - garage-network

  # Service Web Server (Nginx)
  web:
    image: nginx:alpine
    container_name: garage-web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - garage-network

  # Service Base de Données (MySQL)
  db:
    image: mysql:8.0
    container_name: garage-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-garage-kagnan}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME:-kagnan}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - garage-network

  # Service Cache & Session (Redis)
  redis:
    image: redis:alpine
    container_name: garage-redis
    restart: unless-stopped
    networks:
      - garage-network

networks:
  garage-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
